"""Markdown 格式化器

提供財務報表的 Markdown 格式化功能。

V4.1.1 輸出規範：
- 禁止動態欄位：generated_at 只能在 .meta.json
- 固定格式欄位：
  - 金額：整數元 + 千分位（如 1,234,567）
  - 百分比：帶正負號（如 +10%, -5%）
  - 日期：YYYY/MM 格式
- 去噪策略：確保快照測試穩定
"""

from decimal import Decimal

from life_capital.models.scenario import ProjectionResult, ScenarioComparisonResult


class MarkdownFormatter:
    """Markdown 格式化器（V4.1.1 輸出規範）

    提供符合 Contract 6 規範的 Markdown 輸出。
    """

    @staticmethod
    def format_amount(amount: Decimal) -> str:
        """格式化金額（V4.1.1: 固定格式）

        Args:
            amount: 金額（Decimal）

        Returns:
            格式化後的金額字串（如 "1,234,567 元"）
        """
        # 整數元 + 千分位分隔符
        int_amount = int(amount)
        return f"{int_amount:,} 元"

    @staticmethod
    def format_percentage(value: Decimal) -> str:
        """格式化百分比（V4.1.1: 帶正負號）

        Args:
            value: 百分比值（如 0.1 代表 +10%）

        Returns:
            格式化後的百分比字串（如 "+10%"）
        """
        percent = value * 100
        sign = "+" if percent >= 0 else ""
        return f"{sign}{percent:.0f}%"

    @staticmethod
    def format_month(year: int, month: int) -> str:
        """格式化月份（V4.1.1: YYYY/MM）

        Args:
            year: 年份
            month: 月份（1-12）

        Returns:
            格式化後的月份字串（如 "2026/01"）
        """
        return f"{year}/{month:02d}"

    @staticmethod
    def format_status_icon(is_deficit: bool, is_depleted: bool = False) -> str:
        """格式化狀態圖示

        Args:
            is_deficit: 是否為赤字月份
            is_depleted: 是否已資產耗盡

        Returns:
            狀態圖示（✅ 正常 | ⚠️ 赤字 | ❌ 耗盡）
        """
        if is_depleted:
            return "❌"
        elif is_deficit:
            return "⚠️"
        else:
            return "✅"

    def format_monthly_summary(self, projection: ProjectionResult) -> str:
        """格式化月度現金流摘要（V4.1.1 規範）

        Args:
            projection: Phase 2 預測結果

        Returns:
            Markdown 格式的月度摘要
        """
        # 計算關鍵指標
        deficit_count = len(projection.deficit_months)
        has_depletion = projection.asset_depletion_month is not None

        # 生成狀態說明
        if has_depletion:
            year, month = projection.asset_depletion_month
            status = f"⚠️ 資產耗盡月份：{self.format_month(year, month)}"
        else:
            status = "✅ 財務狀況穩健，無資產耗盡風險"

        # V4.1.1: 不包含 generated_at（只在 .meta.json）
        return f"""# 財務預測摘要

**預測期間**: {len(projection.monthly_projections)} 個月

## 關鍵指標

| 指標 | 數值 |
|------|------|
| 總收入 | {self.format_amount(projection.total_income)} |
| 總支出 | {self.format_amount(projection.total_expenses)} |
| 期末儲蓄 | {self.format_amount(projection.final_cumulative_savings)} |
| 平均月現金流 | {self.format_amount(projection.average_monthly_cashflow)} |
| 赤字月數 | {deficit_count} |

## 狀態

{status}

---
*Generated by Life Capital v2.0-phase3*
"""

    def format_projection_table(
        self, projection: ProjectionResult, max_months: int = 12
    ) -> str:
        """格式化預測表（V4.1.1 規範）

        Args:
            projection: Phase 2 預測結果
            max_months: 最多顯示月數（預設 12 個月）

        Returns:
            Markdown 格式的預測表
        """
        rows = []
        for mp in projection.monthly_projections[:max_months]:
            status = self.format_status_icon(
                is_deficit=mp.is_deficit, is_depleted=mp.cumulative_savings < 0
            )
            rows.append(
                f"| {self.format_month(mp.year, mp.month)} "
                f"| {self.format_amount(mp.income)} "
                f"| {self.format_amount(mp.total_expenses)} "
                f"| {self.format_amount(mp.net_cashflow)} "
                f"| {self.format_amount(mp.cumulative_savings)} "
                f"| {status} |"
            )

        # V4.1.1: 不包含 generated_at
        return f"""# 月度預測明細

| 年/月 | 收入 | 支出 | 淨現金流 | 累積儲蓄 | 狀態 |
|-------|------|------|----------|----------|------|
{chr(10).join(rows)}

**狀態圖例**: ✅ 正常 | ⚠️ 赤字 | ❌ 耗盡

---
*Generated by Life Capital v2.0-phase3*
"""

    def format_scenario_comparison(
        self, comparison: ScenarioComparisonResult
    ) -> str:
        """格式化情境比較（V4.1.1 規範）

        Args:
            comparison: Phase 2 情境比較結果

        Returns:
            Markdown 格式的情境比較
        """
        # 生成情境假設表
        assumption_rows = []
        for scenario in comparison.scenarios:
            s = scenario.scenario
            income_change = self.format_percentage(s.income_change_percent)
            expense_change = self.format_percentage(s.expense_change_percent)
            assumption_rows.append(
                f"| {s.name} | {income_change} | {expense_change} | {s.description} |"
            )

        # 生成結果比較表
        result_rows = []
        table = comparison.comparison_table

        # 處理各情境
        for row in table.get("scenarios", []):
            name = row["name"]
            final_savings = Decimal(str(row["final_savings"]))
            deficit_months = row.get("deficit_months", [])
            deficit_count = (
                len(deficit_months) if isinstance(deficit_months, list) else deficit_months
            )

            # 計算 vs 基準差異
            if row.get("diff_savings"):
                diff = Decimal(str(row["diff_savings"]))
                diff_str = self.format_amount(diff) if diff != 0 else "-"
            else:
                diff_str = "-"

            # 資產耗盡狀態
            depletion = row.get("asset_depletion")
            if depletion:
                depletion_str = f"❌ {depletion[0]}/{depletion[1]:02d}"
            else:
                depletion_str = "✅ 安全"

            result_rows.append(
                f"| {name} | {self.format_amount(final_savings)} | {diff_str} "
                f"| {deficit_count} | {depletion_str} |"
            )

        # V4.1.1: 不包含 generated_at
        return f"""# 情境分析比較

## 情境假設

| 情境 | 收入變動 | 支出變動 | 說明 |
|------|----------|----------|------|
{chr(10).join(assumption_rows)}

## 結果比較

| 情境 | 最終儲蓄 | vs 基準 | 赤字月數 | 資產耗盡 |
|------|----------|---------|----------|----------|
{chr(10).join(result_rows)}

**基準線**: {comparison.baseline_name}

---
*Generated by Life Capital v2.0-phase3*
"""
